### ISSUE TITLE
Add supplementary overlay view 

### ISSUE THREAD

**Issue by alinradut** [supercomputra/Arale#3]
Hello! I think it would be really neat if we could feed our own view into Arale, to be shown in front of the image view.

At the moment this is difficult to achieve because the image view is added to the view hierarchy only after the header view is added to the scroll view so if we were to add our customizations in a factory method, the image view would be displayed in front of whatever subviews we added.

I attached PR #2 for this if you want to merge it into the repo. Thanks!

**Comment by supercomputra** [comment]
Resolved with https://github.com/supercomputra/Arale/pull/2
